# Generated by Django 2.0.13 on 2019-09-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
