# Generated by Django 2.0.13 on 2019-09-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_productos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
